In [1]:
import numpy as np
A = np.array([[2,4,6], [5,-6,7],[3,2,1]])
B = np.array([[9,-3,4], [3,6,2],[3,3,4]])
C = A + B 
print(C)

[[11  1 10]
 [ 8  0  9]
 [ 6  5  5]]


# Maxtrix subtraction


In [4]:
import numpy as np
A = np.array([[9,4,6], [5,-6,7],[3,2,1]])
B = np.array([[3,-3,4], [3,4,2],[1,3,4]])
C = A - B     
print(C)

[[  6   7   2]
 [  2 -10   5]
 [  2  -1  -3]]


# Matrix multiplication


In [5]:
import numpy as np
A = np.array([[2,4,6], [5,-6,7],[3,2,1]])
B = np.array([[9,-3,4], [3,6,2],[3,3,4]])
C = A * B     
print(C)

[[ 18 -12  24]
 [ 15 -36  14]
 [  9   6   4]]
