# DOT Product


In [5]:
import numpy as np
vector_a = np.array([[1, 4], [5, 6]])
vector_b = np.array([[2, 4], [5, 2]])
product = np.dot(vector_a, vector_b)
print("Dot Product  :\n", product)
product = np.dot(vector_b, vector_a)
print("Dot Product  :\n", product)


Dot Product  :
 [[22 12]
 [40 32]]
Dot Product  :
 [[22 32]
 [15 32]]


# 3D Dot Product

In [12]:
import numpy as np
vector_a = np.array([[1,4,2],[5,6,4],[4,5,3]])
vector_b = np.array([[2,4,6],[5,2,7],[5,6,1]])
product = np.dot(vector_a,vector_b)
print("Dot Product  :\n", product)
product = np.dot(vector_b, vector_a)
print("Dot Product  :\n", product)

Dot Product  :
 [[32 24 36]
 [60 56 76]
 [48 44 62]]
Dot Product  :
 [[46 62 38]
 [43 67 39]
 [39 61 37]]
